name: enable-ghas
on:
  workflow_dispatch:
    inputs:
      name_filter:
        description: 'Regex filter for repo names'
        required: false
        default: '.*'
      dry_run:
        description: 'WhatIf mode'
        required: false
        default: 'true'
jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable GHAS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ORG:   ${{ secrets.GH_ORG }}
          NAME_FILTER: ${{ inputs.name_filter }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          pwsh ./scripts/enable_ghas.ps1 -Org "$GH_ORG" -NameFilter "$NAME_FILTER" -WhatIf:($DRY_RUN == 'true')
