name: export-alerts
on:
  # schedule: [{ cron: "0 2 * * *" }]  # ⬅️ Disabled for public repo
  workflow_dispatch: {}
permissions:
  contents: write
concurrency:
  group: export-alerts
  cancel-in-progress: true
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Export alerts JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ORG:   ${{ secrets.GH_ORG || 'your-org-name' }}
        run: python scripts/export_code_scanning.py
      - name: Summarize to Markdown
        run: python scripts/summarize_alerts.py
      - name: Commit artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        run: |
          set -euo pipefail
          BRANCH="${{ github.ref_name || 'main' }}"
          git config user.name "ghas-bot"
          git config user.email "actions@users.noreply.github.com"
          git checkout "$BRANCH" || git checkout -b "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git add dashboard/data/alerts.json reports/code_scanning_summary.md || true
          git commit -m "Update code scanning rollup" || echo "No changes to commit"
          if [ "$BRANCH" = "main" ]; then
            git push origin "$BRANCH"
          else
            echo "Not on main (on '$BRANCH'); skipping push."
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-scanning-reports
          path: |
            dashboard/data/alerts.json
            reports/code_scanning_summary.md
